name = "hqt"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "dist"

[env.production]
[[env.production.kv_namespaces]]
binding = "HONGQINGTING_KV"
id = "845d11a4d216470282cc79237e20acec"

[env.preview]
[[env.preview.kv_namespaces]]
binding = "HONGQINGTING_KV"
id = "845d11a4d216470282cc79237e20acec"

[env.production.vars]
ENVIRONMENT = "production"

[env.preview.vars]
ENVIRONMENT = "preview"