name = "hongqingting"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = "dist"

# KV namespace bindings
[[kv_namespaces]]
binding = "HONGQINGTING_KV"
preview_id = "845d11a4d216470282cc79237e20acec"
id = "845d11a4d216470282cc79237e20acec"

# Environment variables (optional)
[env.production.vars]
ENVIRONMENT = "production"

[env.preview.vars]
ENVIRONMENT = "preview"